name: Rust CI/CD

on:
  push:
    branches: [ "master", "feat/cicd" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build Ferrox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable 

      - name: Build Binary
        run: cargo build --release --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ferrox-linux-binary
          path: target/release/ferrox
          if-no-files-found: error